import os

from setuptools import find_packages, setup
from setuptools.dist import Distribution

version = None
with open("neuracore/__init__.py", encoding="utf-8") as f:
    for line in f:
        if line.startswith("__version__"):
            version = line.strip().split()[-1][1:-1]
            break
assert version is not None, "Could not find version string"

with open("README.md", encoding="utf-8") as fh:
    long_description = fh.read()


# The prebuilt Rust artefacts are placed under ``neuracore/data_daemon/`` by
# rust/scripts/build_wheel_artefacts.sh before ``python -m build``. They are
# gitignored and absent from a plain checkout and from the standard release
# build (which does not run that script), so their presence is what decides
# whether this is a binary wheel.
_DATA_DAEMON_DIR = os.path.join(os.path.dirname(__file__), "neuracore", "data_daemon")
_RUST_ARTEFACTS = (
    os.path.join(_DATA_DAEMON_DIR, "bin", "data-daemon"),
    os.path.join(_DATA_DAEMON_DIR, "_native_producer.so"),
)
_HAS_RUST_ARTEFACTS = all(os.path.exists(path) for path in _RUST_ARTEFACTS)


class BinaryDistribution(Distribution):
    """Force a platform-specific wheel tag when the Rust artefacts are bundled.

    The Rust data-daemon binary and producer cdylib shipped under
    ``neuracore/data_daemon/`` are platform-specific, so a wheel that contains
    them must not be tagged ``py3-none-any`` (pip would install a Linux ``.so``
    onto macOS). When the artefacts are absent — e.g. the standard
    ``python -m build`` release, which does not run
    ``build_wheel_artefacts.sh`` — this returns ``False`` so the usual pure
    ``py3-none-any`` wheel is produced and the release pipeline is unchanged.
    See ``docs/rust_data_daemon_development.md#packaging-the-wheel``.
    """

    def has_ext_modules(self) -> bool:
        return _HAS_RUST_ARTEFACTS


setup(
    name="neuracore",
    distclass=BinaryDistribution,
    include_package_data=True,
    package_data={
        "neuracore.data_daemon": [
            # Pre-built Rust artefacts. Generated by
            # rust/scripts/build_wheel_artefacts.sh before `python -m build`.
            # Both paths are gitignored; the wheel build is responsible for
            # placing them. Empty trees just produce an any-platform wheel
            # without these payloads (the Python daemon still works).
            "bin/data-daemon",
            "_native_producer.so",
        ],
    },
    version=version,
    author="Stephen James",
    author_email="support@neuracore.com",
    description="Neuracore Client Library",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/neuracoreai/neuracore",
    packages=find_packages(exclude=["tests*", "examples*"]),
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
    ],
    python_requires=">=3.10",
    install_requires=[
        "numpy>=2.0.0",
        "requests>=2.31.0",
        "pillow>=10.0.0",
        "pyyaml>=6.0.1",
        "tqdm>=4.66.0",
        "requests-oauthlib==2.0.0",
        "pydantic>=2.10",
        "av==15.1.0",
        "aiortc==1.14.0",
        "aiohttp-sse-client==0.2.1",
        "numpy-stl",
        "wget",
        "uvicorn[standard]==0.42.0",
        "fastapi==0.135.2",
        "psutil",
        "typer>=0.20.0",
        "neuracore_types>=9.0.0,<10.0.0",
        "ordered_set",
        "pyzmq==27.1.0",
        "sqlalchemy>=2.0.0",
        "aiosqlite>=0.19.0",
        "aiohttp>=3.9.0",
        "aiofiles>=23.0.0",
        "aiolimiter",
        "pyee==13.0.0",
        "greenlet",
        "filelock>=3.0.0",
        "omegaconf",
        "msgpack>=1.0.8",
    ],
    extras_require={
        "examples": [
            "matplotlib>=3.3.0",
            "mujoco==2.3.7",
            "pyquaternion>=0.9.5",
        ],
        "mjcf": [
            "mujoco>3",
        ],
        "ml": [
            # torch==2.8.0 is minimum version defaulting to CUDA 12.8.
            # Do NOT upgrade to 2.11.0+: it defaults to CUDA 13 which drops
            # V100 support, which Neuracore still uses.
            # hub pinned to 0.35.3 to match lerobot==0.4.4's
            # <0.36.0 constraint, allowing [ml] and [import] to coexist.
            # We have dropped support for P100 and P4 due to CUDA 12.8
            # dropping support for them.
            "torch==2.10.0",
            "torchvision==0.25.0",
            "transformers==4.53.2",
            "huggingface-hub==0.35.3",
            "diffusers==0.35.1",
            "safetensors==0.6.2",
            "einops",
            "hydra-core>=1.3.0",
            "tensorboard>=2",
            "names-generator>=0.2.0",
        ],
        "dev": [
            "pytest>=6.2.5",
            "pytest-cov>=2.12.1",
            "diff-cover",
            "pytest-asyncio>=0.15.1",
            "pytest-xdist",
            "twine>=3.4.2",
            "requests-mock>=1.9.3",
            "pre-commit",
            "types-aiofiles",
            "pyinstrument",
            "plotly",
        ],
        "import": [
            # lerobot is used only for dataset importing
            # (LeRobotDataset/LeRobotDatasetMetadata).
            # Do NOT install lerobot[transformers-dep] — that extra requires
            # transformers>=4.57.1 which conflicts with our transformers==4.53.2 pin.
            # lerobot>=0.4.x drops v2 dataset format support.
            # torch is not pinned here as lerobot==0.4.4 constrains it to
            # >=2.2.1,<2.11.0, compatible with [ml]'s torch==2.10.0.
            # hub pinned to match [ml], allowing both extras to coexist.
            # The importer only uses torch for CPU tensor ops
            # (data loading + .numpy()), so CUDA version does not matter.
            "lerobot==0.4.4",
            "huggingface-hub==0.35.3",
            "tensorflow-datasets>=4.9.9",
            "tensorflow-cpu>=2.20.0",
            "pin==3.9.0",
            "pin-pink==4.2.0",
            "coal==3.0.2",
            "eigenpy==3.12.0",
            "cmeel-boost==1.89.0",
            "cmeel-urdfdom==4.0.1",
            "cmeel-tinyxml2==10.0.0",
            "cmeel-assimp==6.0.5",
            "cmeel-octomap==1.10.0",
            "mcap>=1.3.1,<2",
            "mcap-protobuf-support>=0.5.4,<0.6",
            "mcap-ros1-support>=0.7.4,<0.8",
            "mcap-ros2-support>=0.5.7,<0.6",
        ],
    },
    entry_points={
        "console_scripts": [
            "neuracore = neuracore.core.cli.app:main",
        ]
    },
    keywords="robotics machine-learning ai client-library",
)
