"""Authentication management."""

import logging
import os
from pathlib import Path

import requests
from pydantic import BaseModel, ValidationError

from neuracore.data_daemon.config_manager.daemon_config import DaemonConfig
from neuracore.data_daemon.const import (
    API_URL,
    CONFIG_DIR,
    CONFIG_ENCODING,
    CONFIG_FILE,
)

logger = logging.getLogger(__name__)


class AuthConfig(BaseModel):
    """Authentication configuration model.

    This uses the config file generated by the python frontend to
    share authentication state.

    Attributes:
        api_key: Neuracore API key for authentication.
        current_org_id: Organization ID for the authenticated user.
    """

    api_key: str | None = None
    current_org_id: str | None = None


class AuthenticationError(Exception):
    """Raised when authentication fails."""

    pass


class ConfigError(Exception):
    """Raised when configuration operations fail."""

    pass


class AuthManager:
    """Manages authentication state for the data daemon."""

    def __init__(self, daemon_config: DaemonConfig, config_path: Path | None = None):
        """Initialize the AuthManager.

        Args:
            daemon_config: DaemonConfig instance to store auth values.
            config_path: Path to the auth configuration file.
        """
        if config_path is None:
            config_path = CONFIG_DIR / CONFIG_FILE

        self._config_path = config_path
        self._access_token: str | None = None
        self._config: DaemonConfig = daemon_config

    def _load_config(self) -> None:
        """Load authentication configuration from disk and set on DaemonConfig.

        Raises:
            ConfigError: If there is an error loading the config.
        """
        if not self._config_path.exists():
            logger.error(f"Config file {self._config_path} does not exist")
            return

        try:
            with self._config_path.open("r", encoding=CONFIG_ENCODING) as f:
                config_data = AuthConfig.model_validate_json(f.read())
            # Set auth values on DaemonConfig
            if config_data.api_key:
                self._config.api_key = config_data.api_key
            if config_data.current_org_id:
                self._config.current_org_id = config_data.current_org_id

        except ValidationError as e:
            raise ConfigError(f"Error loading config: invalid structure - {e}")
        except PermissionError as e:
            raise ConfigError(f"Error loading config: insufficient permissions - {e}")
        except UnicodeDecodeError as e:
            raise ConfigError(f"Error loading config: invalid encoding - {e}")
        except OSError as e:
            raise ConfigError(f"Error loading config: cannot open file - {e}")

    @property
    def config(self) -> DaemonConfig:
        """Get the current configuration, loading from disk if necessary.

        Returns:
            The current DaemonConfig.

        Raises:
            ConfigError: If there is an error loading the config.
        """
        self._load_config()
        return self._config

    def get_api_key(self) -> str:
        """Get the API key from environment or config.

        Returns:
            The API key.

        Raises:
            AuthenticationError: If no API key is available.
        """
        _ = self.config

        api_key = os.environ.get("NEURACORE_API_KEY") or self._config.api_key

        if not api_key:
            raise AuthenticationError("No API key found.")

        return api_key

    def get_org_id(self) -> str:
        """Get the organization ID.

        Returns:
            The organization ID.

        Raises:
            AuthenticationError: If no org_id is configured.
        """
        _ = self.config

        if not self._config.current_org_id:
            raise AuthenticationError("No organization ID configured.")

        return self._config.current_org_id

    def get_access_token(self) -> str:
        """Get a valid access token, obtaining a new one if necessary.

        Returns:
            A valid access token.

        Raises:
            AuthenticationError: If token retrieval fails.
        """
        if self._access_token is not None:
            return self._access_token

        api_key = self.get_api_key()

        try:
            response = requests.post(
                f"{API_URL}/auth/verify-api-key",
                json={"api_key": api_key},
                timeout=10,
            )

            if response.status_code != 200:
                raise AuthenticationError(
                    f"Failed to verify API key: {response.status_code}"
                )

            token_data = response.json()
            self._access_token = token_data.get("access_token")

            if not self._access_token:
                raise AuthenticationError("No access token in response")

            return self._access_token

        except requests.exceptions.ConnectionError as e:
            raise AuthenticationError(
                f"Failed to connect to Neuracore server: {e}"
            ) from e
        except requests.exceptions.Timeout as e:
            raise AuthenticationError(f"Request timed out: {e}") from e
        except requests.exceptions.RequestException as e:
            raise AuthenticationError(f"Failed to get access token: {e}") from e

    def get_headers(self) -> dict[str, str]:
        """Get HTTP headers for authenticated API requests.

        Returns:
            Dict containing the Authorization header with bearer token.

        Raises:
            AuthenticationError: If unable to obtain a valid access token.
        """
        access_token = self.get_access_token()
        return {"Authorization": f"Bearer {access_token}"}

    def invalidate_token(self) -> None:
        """Invalidate the current access token."""
        self._access_token = None


_auth: AuthManager | None = None


def initialize_auth(
    daemon_config: DaemonConfig | None = None, config_path: Path | None = None
) -> None:
    """Initialize the global AuthManager instance.

    This is called automatically by get_auth() if not already initialized.
    Can also be called explicitly during daemon startup.

    Args:
        daemon_config: Optional daemon configuration. If not provided,
                      a default DaemonConfig is created.
        config_path: Optional path to config.json file.
    """
    global _auth

    if daemon_config is None:
        daemon_config = DaemonConfig()

    _auth = AuthManager(daemon_config=daemon_config, config_path=config_path)
    logger.info("AuthManager initialized")


def get_auth() -> AuthManager:
    """Get the global AuthManager singleton instance.

    Automatically initializes auth if not already done, loading credentials
    from the python frontend's config file.

    Returns:
        The global AuthManager instance used throughout the application.
    """
    if _auth is None:
        logger.debug("AuthManager not initialized, initializing now")
        initialize_auth()

    assert _auth is not None  # For mypy
    return _auth
