import pathlib

### Environment parameters
EPISODE_LENGTH = 400

### Simulation envs fixed constants
DT = 0.02
START_ARM_POSE = [
    0,
    -0.96,
    1.16,
    0,
    -0.3,
    0,
    0.02239,
    -0.02239,
    0,
    -0.96,
    1.16,
    0,
    -0.3,
    0,
    0.02239,
    -0.02239,
]

THIS_DIR = pathlib.Path(__file__).parent.resolve()
ROBOT_ASSETS = THIS_DIR / "assets" / "robots"
VX300S_DIR = ROBOT_ASSETS / "vx300s"

BIMANUAL_VIPERX_URDF_PATH = str(VX300S_DIR / "bimanual_viperx_ee_transfer_cube.urdf")


# Left finger position limits (qpos[7]), right_finger = -1 * left_finger
MASTER_GRIPPER_POSITION_OPEN = 0.02417
MASTER_GRIPPER_POSITION_CLOSE = 0.01244
PUPPET_GRIPPER_POSITION_OPEN = 0.05800
PUPPET_GRIPPER_POSITION_CLOSE = 0.01844

# Gripper joint limits (qpos[6])
MASTER_GRIPPER_JOINT_OPEN = 0.3083
MASTER_GRIPPER_JOINT_CLOSE = -0.6842
PUPPET_GRIPPER_JOINT_OPEN = 1.4910
PUPPET_GRIPPER_JOINT_CLOSE = -0.6213

############################ Helper functions ############################


def MASTER_GRIPPER_POSITION_NORMALIZE_FN(x):
    return (x - MASTER_GRIPPER_POSITION_CLOSE) / (
        MASTER_GRIPPER_POSITION_OPEN - MASTER_GRIPPER_POSITION_CLOSE
    )


def PUPPET_GRIPPER_POSITION_NORMALIZE_FN(x):
    return (x - PUPPET_GRIPPER_POSITION_CLOSE) / (
        PUPPET_GRIPPER_POSITION_OPEN - PUPPET_GRIPPER_POSITION_CLOSE
    )


def MASTER_GRIPPER_POSITION_UNNORMALIZE_FN(x):
    return (
        x * (MASTER_GRIPPER_POSITION_OPEN - MASTER_GRIPPER_POSITION_CLOSE)
        + MASTER_GRIPPER_POSITION_CLOSE
    )


def PUPPET_GRIPPER_POSITION_UNNORMALIZE_FN(x):
    return (
        x * (PUPPET_GRIPPER_POSITION_OPEN - PUPPET_GRIPPER_POSITION_CLOSE)
        + PUPPET_GRIPPER_POSITION_CLOSE
    )


def MASTER2PUPPET_POSITION_FN(x):
    return PUPPET_GRIPPER_POSITION_UNNORMALIZE_FN(
        MASTER_GRIPPER_POSITION_NORMALIZE_FN(x)
    )


def MASTER_GRIPPER_JOINT_NORMALIZE_FN(x):
    return (x - MASTER_GRIPPER_JOINT_CLOSE) / (
        MASTER_GRIPPER_JOINT_OPEN - MASTER_GRIPPER_JOINT_CLOSE
    )


def PUPPET_GRIPPER_JOINT_NORMALIZE_FN(x):
    return (x - PUPPET_GRIPPER_JOINT_CLOSE) / (
        PUPPET_GRIPPER_JOINT_OPEN - PUPPET_GRIPPER_JOINT_CLOSE
    )


def MASTER_GRIPPER_JOINT_UNNORMALIZE_FN(x):
    return (
        x * (MASTER_GRIPPER_JOINT_OPEN - MASTER_GRIPPER_JOINT_CLOSE)
        + MASTER_GRIPPER_JOINT_CLOSE
    )


def PUPPET_GRIPPER_JOINT_UNNORMALIZE_FN(x):
    return (
        x * (PUPPET_GRIPPER_JOINT_OPEN - PUPPET_GRIPPER_JOINT_CLOSE)
        + PUPPET_GRIPPER_JOINT_CLOSE
    )


def MASTER2PUPPET_JOINT_FN(x):
    return PUPPET_GRIPPER_JOINT_UNNORMALIZE_FN(MASTER_GRIPPER_JOINT_NORMALIZE_FN(x))


def MASTER_GRIPPER_VELOCITY_NORMALIZE_FN(x):
    return x / (MASTER_GRIPPER_POSITION_OPEN - MASTER_GRIPPER_POSITION_CLOSE)


def PUPPET_GRIPPER_VELOCITY_NORMALIZE_FN(x):
    return x / (PUPPET_GRIPPER_POSITION_OPEN - PUPPET_GRIPPER_POSITION_CLOSE)


def MASTER_POS2JOINT(x):
    return (
        MASTER_GRIPPER_POSITION_NORMALIZE_FN(x)
        * (MASTER_GRIPPER_JOINT_OPEN - MASTER_GRIPPER_JOINT_CLOSE)
        + MASTER_GRIPPER_JOINT_CLOSE
    )


def MASTER_JOINT2POS(x):
    return MASTER_GRIPPER_POSITION_UNNORMALIZE_FN(
        (x - MASTER_GRIPPER_JOINT_CLOSE)
        / (MASTER_GRIPPER_JOINT_OPEN - MASTER_GRIPPER_JOINT_CLOSE)
    )


def PUPPET_POS2JOINT(x):
    return (
        PUPPET_GRIPPER_POSITION_NORMALIZE_FN(x)
        * (PUPPET_GRIPPER_JOINT_OPEN - PUPPET_GRIPPER_JOINT_CLOSE)
        + PUPPET_GRIPPER_JOINT_CLOSE
    )


def PUPPET_JOINT2POS(x):
    return PUPPET_GRIPPER_POSITION_UNNORMALIZE_FN(
        (x - PUPPET_GRIPPER_JOINT_CLOSE)
        / (PUPPET_GRIPPER_JOINT_OPEN - PUPPET_GRIPPER_JOINT_CLOSE)
    )


MASTER_GRIPPER_JOINT_MID = (MASTER_GRIPPER_JOINT_OPEN + MASTER_GRIPPER_JOINT_CLOSE) / 2
