# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: src/neuracore_new_data_format/protos/neuracore_new_data_format.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    "",
    "src/neuracore_new_data_format/protos/neuracore_new_data_format.proto",
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\nDsrc/neuracore_new_data_format/protos/neuracore_new_data_format.proto\x12\x19neuracore_new_data_format"+\n\nFloatArray\x12\x0e\n\x06values\x18\x01 \x03(\x02\x12\r\n\x05shape\x18\x02 \x03(\x03"\x9f\x02\n\tJointData\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12@\n\x06values\x18\x02 \x03(\x0b\x32\x30.neuracore_new_data_format.JointData.ValuesEntry\x12U\n\x11\x61\x64\x64itional_values\x18\x03 \x03(\x0b\x32:.neuracore_new_data_format.JointData.AdditionalValuesEntry\x1a-\n\x0bValuesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\x1a\x37\n\x15\x41\x64\x64itionalValuesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01"\xbf\x01\n\x0e\x43\x61meraMetadata\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12\x11\n\tcamera_id\x18\x02 \x01(\t\x12\x11\n\tframe_idx\x18\x03 \x01(\x03\x12\x39\n\nextrinsics\x18\x04 \x03(\x0b\x32%.neuracore_new_data_format.FloatArray\x12\x39\n\nintrinsics\x18\x05 \x03(\x0b\x32%.neuracore_new_data_format.FloatArray"X\n\nCameraData\x12;\n\x08metadata\x18\x01 \x01(\x0b\x32).neuracore_new_data_format.CameraMetadata\x12\r\n\x05\x66rame\x18\x02 \x01(\x0c"\x19\n\tVideoBlob\x12\x0c\n\x04\x62lob\x18\x01 \x01(\x0c"/\n\x0cLanguageData\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12\x0c\n\x04text\x18\x02 \x01(\t"@\n\nCustomData\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\tjson_data\x18\x03 \x01(\tb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR,
    "src.neuracore_new_data_format.protos.neuracore_new_data_format_pb2",
    _globals,
)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_JOINTDATA_VALUESENTRY"]._loaded_options = None
    _globals["_JOINTDATA_VALUESENTRY"]._serialized_options = b"8\001"
    _globals["_JOINTDATA_ADDITIONALVALUESENTRY"]._loaded_options = None
    _globals["_JOINTDATA_ADDITIONALVALUESENTRY"]._serialized_options = b"8\001"
    _globals["_FLOATARRAY"]._serialized_start = 99
    _globals["_FLOATARRAY"]._serialized_end = 142
    _globals["_JOINTDATA"]._serialized_start = 145
    _globals["_JOINTDATA"]._serialized_end = 432
    _globals["_JOINTDATA_VALUESENTRY"]._serialized_start = 330
    _globals["_JOINTDATA_VALUESENTRY"]._serialized_end = 375
    _globals["_JOINTDATA_ADDITIONALVALUESENTRY"]._serialized_start = 377
    _globals["_JOINTDATA_ADDITIONALVALUESENTRY"]._serialized_end = 432
    _globals["_CAMERAMETADATA"]._serialized_start = 435
    _globals["_CAMERAMETADATA"]._serialized_end = 626
    _globals["_CAMERADATA"]._serialized_start = 628
    _globals["_CAMERADATA"]._serialized_end = 716
    _globals["_VIDEOBLOB"]._serialized_start = 718
    _globals["_VIDEOBLOB"]._serialized_end = 743
    _globals["_LANGUAGEDATA"]._serialized_start = 745
    _globals["_LANGUAGEDATA"]._serialized_end = 792
    _globals["_CUSTOMDATA"]._serialized_start = 794
    _globals["_CUSTOMDATA"]._serialized_end = 858
# @@protoc_insertion_point(module_scope)
