"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class FloatArray(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALUES_FIELD_NUMBER: builtins.int
    SHAPE_FIELD_NUMBER: builtins.int
    @property
    def values(
        self,
    ) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[
        builtins.float
    ]: ...
    @property
    def shape(
        self,
    ) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[
        builtins.int
    ]: ...
    def __init__(
        self,
        *,
        values: collections.abc.Iterable[builtins.float] | None = ...,
        shape: collections.abc.Iterable[builtins.int] | None = ...,
    ) -> None: ...
    def ClearField(
        self, field_name: typing.Literal["shape", b"shape", "values", b"values"]
    ) -> None: ...

global___FloatArray = FloatArray

@typing.final
class JointData(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class ValuesEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.float
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.float = ...,
        ) -> None: ...
        def ClearField(
            self, field_name: typing.Literal["key", b"key", "value", b"value"]
        ) -> None: ...

    @typing.final
    class AdditionalValuesEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.float
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.float = ...,
        ) -> None: ...
        def ClearField(
            self, field_name: typing.Literal["key", b"key", "value", b"value"]
        ) -> None: ...

    TIMESTAMP_FIELD_NUMBER: builtins.int
    VALUES_FIELD_NUMBER: builtins.int
    ADDITIONAL_VALUES_FIELD_NUMBER: builtins.int
    timestamp: builtins.float
    @property
    def values(
        self,
    ) -> google.protobuf.internal.containers.ScalarMap[
        builtins.str, builtins.float
    ]: ...
    @property
    def additional_values(
        self,
    ) -> google.protobuf.internal.containers.ScalarMap[
        builtins.str, builtins.float
    ]: ...
    def __init__(
        self,
        *,
        timestamp: builtins.float = ...,
        values: collections.abc.Mapping[builtins.str, builtins.float] | None = ...,
        additional_values: (
            collections.abc.Mapping[builtins.str, builtins.float] | None
        ) = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "additional_values",
            b"additional_values",
            "timestamp",
            b"timestamp",
            "values",
            b"values",
        ],
    ) -> None: ...

global___JointData = JointData

@typing.final
class CameraMetadata(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TIMESTAMP_FIELD_NUMBER: builtins.int
    CAMERA_ID_FIELD_NUMBER: builtins.int
    FRAME_IDX_FIELD_NUMBER: builtins.int
    EXTRINSICS_FIELD_NUMBER: builtins.int
    INTRINSICS_FIELD_NUMBER: builtins.int
    timestamp: builtins.float
    camera_id: builtins.str
    frame_idx: builtins.int
    @property
    def extrinsics(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        global___FloatArray
    ]: ...
    @property
    def intrinsics(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        global___FloatArray
    ]: ...
    def __init__(
        self,
        *,
        timestamp: builtins.float = ...,
        camera_id: builtins.str = ...,
        frame_idx: builtins.int = ...,
        extrinsics: collections.abc.Iterable[global___FloatArray] | None = ...,
        intrinsics: collections.abc.Iterable[global___FloatArray] | None = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "camera_id",
            b"camera_id",
            "extrinsics",
            b"extrinsics",
            "frame_idx",
            b"frame_idx",
            "intrinsics",
            b"intrinsics",
            "timestamp",
            b"timestamp",
        ],
    ) -> None: ...

global___CameraMetadata = CameraMetadata

@typing.final
class CameraData(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    METADATA_FIELD_NUMBER: builtins.int
    FRAME_FIELD_NUMBER: builtins.int
    frame: builtins.bytes
    @property
    def metadata(self) -> global___CameraMetadata: ...
    def __init__(
        self,
        *,
        metadata: global___CameraMetadata | None = ...,
        frame: builtins.bytes = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing.Literal["metadata", b"metadata"]
    ) -> builtins.bool: ...
    def ClearField(
        self, field_name: typing.Literal["frame", b"frame", "metadata", b"metadata"]
    ) -> None: ...

global___CameraData = CameraData

@typing.final
class VideoBlob(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BLOB_FIELD_NUMBER: builtins.int
    blob: builtins.bytes
    def __init__(
        self,
        *,
        blob: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["blob", b"blob"]) -> None: ...

global___VideoBlob = VideoBlob

@typing.final
class LanguageData(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TIMESTAMP_FIELD_NUMBER: builtins.int
    TEXT_FIELD_NUMBER: builtins.int
    timestamp: builtins.float
    text: builtins.str
    def __init__(
        self,
        *,
        timestamp: builtins.float = ...,
        text: builtins.str = ...,
    ) -> None: ...
    def ClearField(
        self, field_name: typing.Literal["text", b"text", "timestamp", b"timestamp"]
    ) -> None: ...

global___LanguageData = LanguageData

@typing.final
class CustomData(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TIMESTAMP_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    JSON_DATA_FIELD_NUMBER: builtins.int
    timestamp: builtins.float
    name: builtins.str
    json_data: builtins.str
    """JSON-encoded data"""
    def __init__(
        self,
        *,
        timestamp: builtins.float = ...,
        name: builtins.str = ...,
        json_data: builtins.str = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "json_data", b"json_data", "name", b"name", "timestamp", b"timestamp"
        ],
    ) -> None: ...

global___CustomData = CustomData
