name: Integration ML - Dataset Mutation Training (Staging)

on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:

jobs:
  test:
    uses: NeuracoreAI/shared-workflows/.github/workflows/integration-ml-test.yaml@main
    with:
      environment: staging
      test-path: tests/integration/ml/test_dataset_mutation_training.py
    secrets: inherit
