name: Integration ML - Deleted Dataset Resume (Production)

on:
  schedule:
    - cron: "0 0 * * *"  # 7. test_deleted_dataset_on_resume_training.py
  workflow_dispatch:

jobs:
  test:
    uses: NeuracoreAI/shared-workflows/.github/workflows/integration-ml-test.yaml@main
    with:
      environment: production
      test-path: tests/integration/ml/test_deleted_dataset_on_resume_training.py::test_resume_fails_when_training_dataset_has_been_deleted
    secrets: inherit
