name: ML Integration Tests

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - uses: pre-commit/action@v3.0.1

  test:
    needs: pre-commit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']
        environment: [staging, production]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Pull LFS objects
      run: git lfs pull
      
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ".[dev,ml,examples]"

    - name: Run Integration Test
      env:
        NEURACORE_API_URL: ${{ matrix.environment == 'staging' && 'https://api.staging.neuracore.app/api' || 'https://api.neuracore.app/api' }}
        NEURACORE_API_KEY: ${{ matrix.environment == 'staging' && secrets.STAGING_SERVICE_API_KEY || secrets.PROD_SERVICE_API_KEY }}
        NEURACORE_ORG_ID: ${{ matrix.environment == 'staging' && vars.STAGING_SERVICE_ORG_ID || vars.PROD_SERVICE_ORG_ID }}
      run: |
        xvfb-run -a pytest -o log_cli=true --log-cli-level=INFO -v -n auto tests/integration/test_algorithm.py
