name: Nightly Integration Tests

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - uses: pre-commit/action@v3.0.1

  test:
    needs: pre-commit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ".[dev,ml]"

    - name: Run Integration Test
      env:
        NEURACORE_API_URL: "https://staging.api.neuracore.app/api"
        SERVICE_ORG: ${{ vars.SERVICE_ORG }}
        NEURACORE_API_KEY: ${{ secrets.SERVICE_ACCOUNT_API_KEY }}
      run: |
        nc-select-org --org-id="$SERVICE_ORG"
        pytest tests/integration/test_consume_stream.py::test_get_latest_data_from_multiple_nodes